### ISSUE TITLE
能否提供完整的Experiences*.csv文件

### ISSUE THREAD

**Issue by LJianlin** [AsprinChina/L2RPN_NIPS_2020_a_PPO_Solution#2]
我尝试run Teacher1.py时发现，贪婪搜索消耗的时间太长，以至于我使用多进程运行一天的时间都不能完整探索所有的chronics，生成Experiences*.csv文件时间花费太过庞大，所以想问下能否提供能否提供完整的Experiences*.csv文件，万分感谢。

**Comment by Aspirin96** [comment]
文件很大，而且在内网，我目前也拿不到。

**Comment by LJianlin** [comment]
好的，感谢回复，那我自己评估下，采样大概需要消耗什么样的算力和时间吧
