### ISSUE TITLE
How I can find the paper published about the challenge?

### ISSUE THREAD

**Issue by aut6620** [AsprinChina/L2RPN_NIPS_2020_a_PPO_Solution#4]
I  want to study this paper, can you tell me where  I  can get this paper?

**Comment by Aspirin96** [comment]
This is the offical document about the L2RPN challenge: http://proceedings.mlr.press/v133/marot21a.html.

**Comment by aut6620** [comment]
Thanks for your reply. And can I bother to know weather your team published the paper using this method. your team ranked second,after all. if yes,can I know how I get the paper or link.

**Comment by Aspirin96** [comment]
In fact, we didn't do that due to some reasons. The codes and slides (in the attached video) are the all available now.

**Comment by aut6620** [comment]
Fine, thanks for your reply.
